### ISSUE TITLE
[item6] 유한 상태 머신이란 무엇일까 ?

### ISSUE THREAD

**Issue by pjhsk113** [Effective-Tilinkle/effective-java#8]
> Pattern은 정규표현식에 해당하는 유한 상태 머신을 만들기 때문에 인스턴스 생성 비용이 높다.

유한 상태 머신이 무엇이고 왜 인스턴스 생성 비용이 높아지는 걸까요?
다시 봐도 어렵네용..ㅠㅠ

**Comment by HwangSeonHo** [comment]
유한 상태 머신은 게임 캐릭터 상태를 생각하시면 편할 것 같습니다.
예를 들어 캐릭터는 정지 이동 공격 이런 각각의 상태를 한번에 하나씩 가질 수 있고
이벤트에 따라 각 상태로 전이되며 상태에 맞는 행동을 합니다.
이렇게 상태를 가지고 이벤트에따라 전이하며 각각의 행동을 하는 걸 유한 상태 머신이라고 알고있습니다.

정지 이동 공격 뿐이라면 그다지 많은 상태도 아니고 인스턴스도 적지만
정규 표현식을 생각해보면 0~9 A~Z ㄱ~ㅎ 등등 표현식 각각 모두 하나의 상태가 되므로 상태별로 하나씩의 인스턴스를 가지게 될 것 같습니다.

**Comment by makga87** [comment]
> > Pattern은 정규표현식에 해당하는 유한 상태 머신을 만들기 때문에 인스턴스 생성 비용이 높다.
> 
> 유한 상태 머신이 무엇이고 왜 인스턴스 생성 비용이 높아지는 걸까요? 다시 봐도 어렵네용..ㅠㅠ

해당 내용 보고 저도 좀 찾아보니, 선호님 말과 동일한 내용이 많습니다.

자바 코드로 재현해보면, 무상태 -> A 상태에서 입력값에 따라 -> B 상태, C 상태 입력값에 따라 -> D 상태 등의 인스턴스가 만들어지도록 개발이 됩니다. (그래프와 같은 모양이 되는?)

정규표현식은 곧 유한상태머신과 연관이 지어지는 이유는, 정규표현식 내부에 적힌 값들 하나하나가 각 상태를 의미하고(이는 선호님 답변처럼 인스턴스화로 보여집니다), 객체의 깊이가 깊어지게 됩니다. 그리고 내부적으로 메모리에 올려지게 되고요  

즉, 굳이 Pattern이 아니더라도 정규표현식을 쓰게 되면, 인스턴스 생성비용이 높아지는 것이라 보여지네요

P.S : 추가로 다른 블로그를 보니, html도 유한 상태 머신과 연관이 있다고 합니다. 각 태그가 열리고 닫히는 부분이 바로 그것이라고 하네요?

**Comment by KimJeongHoon3** [comment]
스프링에서도 상태머신을 잘 쓸 수 있도록 모듈을 제공해주고 있네요
https://dealicious-inc.github.io/2021/04/12/state-machine.html

근데, `Pattern`클래스의 코드레벨에서 상태머신이 어떤식으로 쓰였는지는 잘 이해가 안가네요 ㅠ 
대상 string을 Matcher가 match 메서드 호출시 상태머신인 Pattern 내부의 Node(tree로 구성)들을 사용해서 매칭여부를 주욱 확인하게 되는것 같은데, 상태머신개념과 같이 이해해보려하는데 어렵네요 ㅠ

@makga87 형근님께서 얼추 이해하신것 같은데, 이따 모임때 설명 부탁드립니다 ㅠ
